### ISSUE TITLE
Add `.file()` method

### ISSUE THREAD

**Issue by Turbo87** [sindresorhus/gzip-size#11]
I think it would be useful to add a `path()` method that did something like:

```js
function path(path, options) {
  return new Promise((resolve, reject) => {
    let stream = fs.createReadStream(path);
    stream.on('error', reject);
    stream.pipe(gzipSize.stream(options)).on('gzip-size', resolve);
  });
}
```

Would that be a welcome PR?

**Comment by sindresorhus** [comment]
Yes, that would be welcomed. Should be named `.file()` though, and remember to also add an error handler on the `gzipSize.stream` (Errors doesn't propagate in Node.js streams...).
